-- MySQL Script generated by MySQL Workbench
-- vie 17 may 2019 12:53:03 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema buzzflix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema buzzflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buzzflix` DEFAULT CHARACTER SET latin1 ;
USE `buzzflix` ;

-- -----------------------------------------------------
-- Table `buzzflix`.`quizz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buzzflix`.`quizz` (
  `id` INT(50) NOT NULL AUTO_INCREMENT,
  `creador` INT(50) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `contenido` VARCHAR(20000) NULL DEFAULT NULL,
  `estrellas` INT(50) NOT NULL,
  `fechacreacion` DATE NOT NULL,
  `publicado` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `buzzflix`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buzzflix`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `avatar` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `buzzflix`.`moderacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buzzflix`.`moderacion` (
  `quizz` INT(50) NOT NULL,
  `usuario` INT(11) NOT NULL,
  `decision` INT(50) NOT NULL,
  PRIMARY KEY (`quizz`, `usuario`),
  INDEX `fk_moderacion_users1_idx` (`usuario` ASC),
  CONSTRAINT `fk_moderacion_quizz1`
    FOREIGN KEY (`quizz`)
    REFERENCES `buzzflix`.`quizz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moderacion_users1`
    FOREIGN KEY (`usuario`)
    REFERENCES `buzzflix`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `buzzflix`.`votaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buzzflix`.`votaciones` (
  `origen` INT(11) NOT NULL,
  `quizz` INT(50) NOT NULL,
  `cantidad` INT(10) NOT NULL,
  PRIMARY KEY (`quizz`, `origen`),
  INDEX `fk_votaciones_users1_idx` (`origen` ASC),
  INDEX `fk_votaciones_quizz1_idx` (`quizz` ASC),
  CONSTRAINT `fk_votaciones_users1`
    FOREIGN KEY (`origen`)
    REFERENCES `buzzflix`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votaciones_quizz1`
    FOREIGN KEY (`quizz`)
    REFERENCES `buzzflix`.`quizz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `buzzflix`.`follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buzzflix`.`follows` (
  `origen` INT(11) NOT NULL,
  `destino` INT(11) NOT NULL,
  PRIMARY KEY (`origen`, `destino`),
  INDEX `fk_users_has_users_users2_idx` (`destino` ASC),
  INDEX `fk_users_has_users_users1_idx` (`origen` ASC),
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`origen`)
    REFERENCES `buzzflix`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`destino`)
    REFERENCES `buzzflix`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
